function Invoke-M365DeltaRestore {
    <#
    .SYNOPSIS
        Applies a delta restore using only the files that changed between two snapshots.

    .DESCRIPTION
        Reads a delta manifest (produced by New-M365BackupDelta) and updates the restore
        config to scope the restore to only the Added and Changed files. This lets you
        restore only what actually changed rather than the entire snapshot, minimising
        unintended side-effects.

        Use -ApplyChanges to write the changes to the tenant. Without it the function
        runs in preview mode.

    .PARAMETER DeltaPath
        Path to the delta.manifest.json file generated by New-M365BackupDelta.

    .PARAMETER RestoreConfigPath
        Path to restore.config.json. Defaults to config/restore.config.json.

    .PARAMETER ApplyChanges
        When set, changes are applied to the tenant. Otherwise runs in preview (dry-run) mode.

    .PARAMETER Force
        Suppress confirmation prompts.

    .EXAMPLE
        Invoke-M365DeltaRestore -DeltaPath C:\backup\tenant\snap-new\delta.manifest.json

    .EXAMPLE
        Invoke-M365DeltaRestore -DeltaPath .\delta.manifest.json -ApplyChanges -Force
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$DeltaPath,

        [Parameter()]
        [string]$RestoreConfigPath,

        [Parameter()]
        [switch]$ApplyChanges,

        [Parameter()]
        [switch]$Force
    )

    $resolvedDeltaPath = Resolve-BackupM365Path -Path $DeltaPath
    $resolvedRestoreConfigPath = Resolve-BackupM365Path -Path $RestoreConfigPath -DefaultRelativePath 'config/restore.config.json'

    if (-not (Test-Path -Path $resolvedDeltaPath -PathType Leaf)) {
        throw "Delta manifest not found: $resolvedDeltaPath"
    }
    if (-not (Test-Path -Path $resolvedRestoreConfigPath -PathType Leaf)) {
        throw "Restore config not found: $resolvedRestoreConfigPath"
    }

    $delta = Get-Content -Path $resolvedDeltaPath -Raw | ConvertFrom-Json -ErrorAction Stop
    $restoreConfig = Get-Content -Path $resolvedRestoreConfigPath -Raw | ConvertFrom-Json -ErrorAction Stop

    $changedFiles = @($delta.Items | Where-Object { $_.Status -in @('Added', 'Changed') } | Select-Object -ExpandProperty RelativePath)
    if ($changedFiles.Count -eq 0) {
        throw 'Delta manifest does not contain any Added or Changed files to restore.'
    }

    $restoreConfig.scope.mode = 'File'
    $restoreConfig.scope.files = $changedFiles

    $tempConfigPath = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath ("restore-delta-{0}.json" -f ([guid]::NewGuid().ToString('N')))
    $restoreConfig | ConvertTo-Json -Depth 30 | Set-Content -Path $tempConfigPath -Encoding UTF8

    try {
        if ($ApplyChanges) {
            return (Restore-M365TenantConfig -ConfigPath $tempConfigPath -ApplyChanges -Force:$Force)
        }

        return (Restore-M365TenantConfig -ConfigPath $tempConfigPath -DryRun)
    }
    finally {
        if (Test-Path -Path $tempConfigPath) {
            Remove-Item -Path $tempConfigPath -Force -ErrorAction SilentlyContinue
        }
    }
}